language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
env:
  - LARAVEL_VERSION="4.0.x"
  - LARAVEL_VERSION="4.1.x"
  - LARAVEL_VERSION="4.2.x"

before_script:
  - composer self-update
  - composer require illuminate/support:${LARAVEL_VERSION} --no-update
  - composer require illuminate/view:${LARAVEL_VERSION} --no-update
  - composer require illuminate/foundation:${LARAVEL_VERSION} --no-update --dev
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
